# .github/workflows/run-automator.yml
name: Check for Packages

on:
  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

  schedule:
    # Runs 8 times a day at specific times in UTC.
    # This corresponds to 9:15/9:35 AM, 1:01/1:32 PM, 5:06/5:30 PM, and 8:00/8:30 PM
    # in New York (EDT, UTC-4).
    - cron: '15 13 * * *'
    - cron: '35 13 * * *'
    - cron: '1 17 * * *'
    - cron: '32 17 * * *'
    - cron: '6 21 * * *'
    - cron: '30 21 * * *'
    - cron: '0 0 * * *'
    - cron: '30 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Run Package Automator
        run: python main.py
        env:
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          SENDER_ADDRESS: ${{ secrets.SENDER_ADDRESS }}
          FORM_URL: ${{ secrets.FORM_URL }}
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          ROOM_NUMBER: ${{ secrets.ROOM_NUMBER }}

      - name: Upload submission screenshot
        uses: actions/upload-artifact@v4
        with:
          name: submission-screenshot
          path: submission_*.png
